[build-system]
requires = [
    "setuptools>=80.3.1",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "innosoft_app"
version = "0.0.1"
description = "innosoft_app is an app built with SPLENT (https://www.splent.io)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.optional-dependencies]
dev = [
    "watchdog",
]
core = [
    "splent_framework",
]

[tool.splent]
cli_version = "1.21.1"
features = [
    "splent_io/splent_feature_redis@v1.5.7",
    "splent_io/splent_feature_public@v1.7.3",
    "splent_io/splent_feature_session_redis@v1.1.2",
    "splent_io/splent_feature_settings@v0.3.1",
    "splent_io/splent_feature_admin@v1.4.0",
    "splent_io/splent_feature_nginx@v1.2.0",
    "splent_io/splent_feature_skin_arcade@v0.2.2",
    "splent_io/splent_feature_about@v0.2.2",
    "splent_io/splent_feature_theme@v0.11.0",
    "splent_io/splent_feature_media@v0.8.0",
    "splent_io/splent_feature_auth@v1.12.0",
    "splent_io/splent_feature_events@v0.3.0",
]
features_dev = []
features_prod = []
spl = "cms_spl"

[tool.splent.layout]
base_template = "base_template.html"
hooks = [
    "layout.head.css",
    "layout.sidebar.top",
    "layout.anonymous_sidebar",
    "layout.authenticated_sidebar",
    "layout.sidebar.authenticated.items",
    "layout.navbar.anonymous",
    "layout.navbar.authenticated",
    "layout.footer",
    "layout.scripts",
]

[tool.splent.spl_model]
mirror = "uvlhub.io"
doi = "10.5281/zenodo.21923420"
concept_doi = ""
version = ""
file = "cms_spl.uvl"

[tool.splent.config]
AUTH_LOGIN_LAYOUT = "public_base.html"
AUTH_NAV_LOGIN = false
AUTH_FOOTER_LOGIN = true
MEDIA_NAV_LABEL = "Fotos"
EVENTS_NAV_LABEL = "Eventos"
ABOUT_NAV_LABEL = "Quiénes somos"

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = [
    "src",
]
