[build-system]
requires = [
    "setuptools>=80.3.1",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "innosoft_app"
version = "0.0.1"
description = "innosoft_app is an app built with SPLENT (https://www.splent.io)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.optional-dependencies]
dev = [
    "watchdog",
]
core = [
    "splent_framework",
]

[tool.splent]
cli_version = "1.21.1"
features = [
    "splent_io/splent_feature_redis@v1.5.7",
    "splent_io/splent_feature_public",
    "splent_io/splent_feature_session_redis@v1.1.2",
    "splent_io/splent_feature_settings@v0.3.1",
    "splent_io/splent_feature_admin@v1.4.0",
    "splent_io/splent_feature_nginx@v1.2.0",
    "splent_io/splent_feature_skin_arcade",
    "splent_io/splent_feature_about",
    "splent_io/splent_feature_theme",
    "splent_io/splent_feature_media",
    "splent_io/splent_feature_auth",
    "splent_io/splent_feature_events",
    "splent_io/splent_feature_partners",
    "splent_io/splent_feature_team",
    "splent_io/splent_feature_legal",
    "splent_io/splent_feature_contact@v0.2.1",
    "splent_io/splent_feature_mail@v1.4.3",
    "splent_io/splent_feature_cloudflare@v0.1.5",
    "splent_io/splent_feature_map",
    "splent_io/splent_feature_editions",
    "splent_io/splent_feature_post",
    "splent_io/splent_feature_edition_staff",
    "splent_io/splent_feature_survey",
]
features_dev = []
features_prod = []
spl = "cms_spl"

[tool.splent.layout]
base_template = "base_template.html"
hooks = [
    "layout.head.css",
    "layout.sidebar.top",
    "layout.anonymous_sidebar",
    "layout.authenticated_sidebar",
    "layout.sidebar.authenticated.items",
    "layout.navbar.anonymous",
    "layout.navbar.authenticated",
    "layout.footer",
    "layout.scripts",
]

[tool.splent.spl_model]
mirror = "uvlhub.io"
doi = "10.5281/zenodo.21954373"
concept_doi = ""
version = "4"
file = "cms_spl.uvl"

[tool.splent.config]
AUTH_LOGIN_LAYOUT = "public_base.html"
AUTH_NAV_LOGIN = false
AUTH_FOOTER_LOGIN = true
MEDIA_NAV_LABEL = "Fotos"
MEDIA_HOME_COUNT = 6
EVENTS_NAV_LABEL = "Programa"
EDITIONS_NAV_LABEL = "Ediciones"
POST_NAV_LABEL = "Noticias"
POST_INDEX_PATH = "/noticias"
POST_HOME_COUNT = 3
ABOUT_NAV_LABEL = "Quiénes somos"
MAP_QUERY = "Escuela Técnica Superior de Ingeniería Informática, Av. de la Reina Mercedes, s/n, 41012 Sevilla"
MAP_ADDRESS = "Escuela Técnica Superior de Ingeniería Informática. Av. Reina Mercedes s/n, 41012 Sevilla"
BABEL_DEFAULT_LOCALE = "es"
BABEL_SUPPORTED_LOCALES = "es,en"

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = [
    "src",
]
